routes/web.php
<?php

Auth::routes();
/**
 * *******************************************
 * Admin Routes ********************************
 * *******************************************
 */

Route::match(['get','post'],'/admin','AdminController@login')->name('loginAdmin');
Route::get('login','AdminController@loginform');
Route::get('admin/login','AdminController@loginform')->name('login');

Route::group(['middleware' => ['admin', 'auth'], 'namespace' => 'Admin', 'prefix' => 'admin'],function () {
    Route::post('logout','AdminController@logout')->name('adminLogout');
    // dashboard home
    Route::get('dashboard', 'HomeController@index');
    Route::get('importFile', 'HomeController@create');
    Route::post('importFile', 'HomeController@store');

    // Users Routes
    Route::resource('users', 'UsersController');
    Route::get('users/{id}/status', 'UsersController@status');
    Route::get('users/{id}/delete', 'UsersController@destroy');
    Route::post('users_ajax', 'UsersController@users');

    // Managers Routes
    Route::resource('managers', 'ManagersController');
    Route::get('managers/{id}/status', 'ManagersController@status');
    Route::get('managers/{id}/delete', 'ManagersController@destroy');
    Route::post('managers_ajax', 'ManagersController@managers');

    // Dictionaries Routes
    Route::resource('dictionaries', 'DictionariesController');
    Route::get('dictionaries/{id}/status', 'DictionariesController@status');
    Route::get('dictionaries/{id}/delete', 'DictionariesController@destroy');
    Route::post('dictionaries_ajax', 'DictionariesController@dictionaries');

    // Countries Routes
    Route::resource('countries', 'CountriesController');
    Route::get('countries/{id}/status', 'CountriesController@status');
    Route::get('countries/{id}/delete', 'CountriesController@destroy');
    Route::post('countries_ajax', 'CountriesController@countries');

    // Cities Routes
    Route::resource('cities', 'CitiesController');
    Route::get('cities/{id}/status', 'CitiesController@status');
    Route::get('cities/{id}/delete', 'CitiesController@destroy');
    Route::post('cities_ajax', 'CitiesController@cities');

    // Permissions Routes
    Route::resource('roles', 'RolesController');
    Route::post('roles_ajax', 'RolesController@roles');

    // Languages Routes
    Route::resource('languages', 'LanguagesController');
    Route::get('languages/{id}/delete', 'LanguagesController@destroy');
    Route::post('languages_ajax', 'LanguagesController@languages');

    // Jobs Routes
    Route::resource('jobs', 'JobsController');
    Route::get('jobs/{id}/delete', 'JobsController@destroy');
    Route::post('jobs_ajax', 'JobsController@jobs');
     // Jobs Routes
     Route::resource('categories', 'CategoriesController');
     Route::get('categories_new', 'CategoriesController@new_index');
     Route::get('categories/{id}/delete', 'CategoriesController@destroy');
     Route::post('categories_ajax', 'CategoriesController@categories');
     Route::post('categories_ajax/{id}', 'CategoriesController@sub_categories');

     Route::post('sub_categories_dropdown', 'CategoriesController@sub_categories_dropdown');
     
     // Dictionaries Routes
     Route::resource('dictionaries', 'DictionariesController');
     Route::get('dictionaries/{id}/status', 'DictionariesController@status');
     Route::get('dictionaries/{id}/delete', 'DictionariesController@destroy');
     Route::post('dictionaries_ajax', 'DictionariesController@dictionaries');
     // Books Routes
     Route::resource('books', 'BooksController');
     Route::get('books/{id}/status', 'BooksController@status');
     Route::get('books/{id}/delete', 'BooksController@destroy');
     Route::post('books_ajax', 'BooksController@books');
     // words Routes
     Route::get('words_create_file/{id}', 'WordsController@create_file');
     Route::resource('words', 'WordsController');
     Route::resource('dictionary_file', 'DictionaryFileController');
     Route::get('words/{id}/delete', 'WordsController@destroy');
     Route::get('dictionary_file/{id}/delete', 'DictionaryFileController@destroy');
     Route::post('words_ajax', 'WordsController@words');

     Route::get('media/{id}', 'WordsController@media');
     Route::get('examples/{id}', 'WordsController@examples');

     // words Routes
     Route::resource('search', 'SearchController');
     Route::post('results_ajax', 'SearchController@results_ajax');

     // Home Page Slider
     Route::resource('slider', 'SliderController');
     Route::get('slider_text', 'SliderController@slider_text');
     Route::post('slider_text', 'SliderController@save_slider_text');
        
     // Banner Under Slider
     Route::get('banner_under_slider', 'HomePageController@banner');
     Route::post('banner_under_slider', 'HomePageController@save_banner');
        
     // Home Categories Section
     Route::get('categories_section', 'HomePageController@categories_section');
     Route::post('categories_section', 'HomePageController@save_categories_section');   
             
     // Home About Us Section
     Route::get('home_about_us', 'HomePageController@home_about_us');
     Route::post('home_about_us', 'HomePageController@save_home_about_us');  
     Route::resource('home_about_us_sections', 'HomeAboutController');
     
    Route::get('search_words', 'HomePageController@search_words');
    Route::post('search_words', 'HomePageController@save_search_words');      

    Route::get('work_process', 'HomePageController@work_process');
    Route::post('work_process', 'HomePageController@save_work_process');      
    Route::resource('home_work_process_sections', 'HomeProcessController');
});

/**
 * *******************************************
 * Web Routes ********************************
 * *******************************************
 */

Route::group(['middleware' => 'FrontEnd'],function () {
    // Home Page
    Route::get('/', 'HomeController@index');
    // Contact Us
    Route::get('Contact-Us', 'HomeController@contact');
    Route::post('Contact-Us', 'HomeController@send_contact');    
    // Search Words
    Route::get('Search', 'HomeController@search');
    // Library
    Route::get('Library', 'LibraryController@index');    
    Route::get('Library-File/{id}', 'LibraryController@show');        
    // Blog
    Route::get('Blog', 'BlogController@index');    
    Route::get('User-Articles/{id}', 'BlogController@user_articles');
    Route::get('View-Resume/{id}', 'UserController@view_resume');
    Route::get('Article/{id}', 'BlogController@article');            
    // Register
    Route::get('Register', 'UserController@register_form');
    Route::post('Register', 'UserController@register');
    // Login
    Route::post('Login', 'UserController@login');
    Route::get('activate_account/{token}', 'UserController@activate_account');
    // Subscribe
    Route::post('subscribe', 'HomeController@subscribe');
    
    Route::post('word-comments/{id}', 'WordController@word_comments');
    Route::post('word_comment', 'WordController@save_word_comments');

    Route::post('word-suggestions/{id}', 'WordController@word_suggestions');
    Route::post('word_suggestions', 'WordController@save_word_suggestions');
    Route::post('like_suggesations/{id}', 'WordController@like_suggesations');
    Route::post('dislike_suggesations/{id}', 'WordController@dislike_suggesations');

    Route::post('word-articles/{id}', 'WordController@word_articles');


    Route::group(['middleware' => 'auth'],function () {
        Route::get('Profile', 'UserController@profile');

        Route::get('Favourite-Word/{id}', 'UserController@favourite_word');
        Route::post('Favourite-Book/{id}', 'UserController@favourite_book');

        Route::get('Change-Information', 'UserController@change_information');
        Route::post('Change-Information', 'UserController@save_information');
 
        Route::get('Change-Password', 'UserController@change_password');
        Route::post('Change-Password', 'UserController@save_password');

        Route::get('My-Resume', 'UserResumeController@index');
        Route::get('Preview-Resume', 'UserController@preview_resume');
        Route::post('Cover-Letter', 'UserResumeController@cover_letter');

        
        Route::post('New-Education', 'UserResumeController@new_education');
        Route::post('Update-Education/{id}', 'UserResumeController@update_education');
        Route::get('delete_education/{id}', 'UserResumeController@delete_education');

        Route::post('New-Experince', 'UserResumeController@new_experince');
        Route::post('Update-Experince/{id}', 'UserResumeController@update_experince');
        Route::get('delete_experince/{id}', 'UserResumeController@delete_experince');

        Route::post('Skills', 'UserResumeController@skills');
        Route::post('add_skill', 'UserResumeController@add_skill');

        Route::post('Languages', 'UserResumeController@languages');
        Route::post('add_language', 'UserResumeController@add_language');

        Route::post('New-Award', 'UserResumeController@new_award');
        Route::post('Update-Award/{id}', 'UserResumeController@update_award');
        Route::get('delete_award/{id}', 'UserResumeController@delete_award');

        Route::get('My-Blog', 'UserBlogController@index');        
        Route::get('New-Article', 'UserBlogController@create');        
        Route::get('New-Article/{word}', 'UserBlogController@create_wword');
        Route::post('Post-Article', 'UserBlogController@store');        
        Route::get('Edit-Article/{id}', 'UserBlogController@edit');        
        Route::post('Update-Article/{id}', 'UserBlogController@update');        
        Route::get('Delete-Article/{id}', 'UserBlogController@destroy');        
        Route::post('article_comment', 'UserBlogController@article_comment');        
        
        Route::get('My-Library', 'UserLibraryController@index');        

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    //
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Auth;

use Intervention\Image\ImageManagerStatic as Image;


use App\Slider;
use App\SearchSection;

class SliderController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sliders = Slider::get();
        return view('dashboard.slider.index')->with(['sliders'=>$sliders]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'image' => 'required|mimes:jpeg,png,jpg,gif,svg'
        ],
        $messages = [
            'image.required' => 'Please Choose Image',
            'image.mimes' => 'Please Choose Image'
        ]);

        $slider = new Slider;        
        $image = $request->file('image');
        $imageName = time().'.'.$image->getClientOriginalExtension();
        $destinationPath = public_path('/uploads/slider');
        $image->move($destinationPath, $imageName);
        $slider->image ='/uploads/slider/'.$imageName;
        $image = Image::make(public_path().$slider->image)->resize(1920, 700)->save(public_path().$slider->image);

        $slider->save();
        return redirect()->route('slider.index');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slider = Slider::findOrFail($id);
        return view('dashboard.slider.edit')->with(['slider'=>$slider]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $slider = Slider::findOrFail($id);
        if($request->hasFile('image'))
        {
            $validatedData = $request->validate([
                'image' => 'required|mimes:jpeg,png,jpg,gif,svg'
            ],
            $messages = [
                'image.required' => 'Please Choose Image',
                'image.mimes' => 'Please Choose Image'
            ]);

            if (File::exists(public_path().$slider->image))
            {
                File::delete(public_path().$slider->image);
            }

            $image = $request->file('image');
            $imageName = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/uploads/slider');
            $image->move($destinationPath, $imageName);
            $slider->image = '/uploads/slider/'.$imageName;
            $image = Image::make(public_path().$slider->image)->resize(1920, 700)->save(public_path().$slider->image);
        }
        
        $slider->save();
        return redirect()->route('slider.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slider = Slider::findOrFail($id);

        if (File::exists(public_path().$slider->image))
        {
            File::delete(public_path().$slider->image);
        }
        $slider->delete();
        return redirect()->route('slider.index');
    }

    public function slider_text ()
    {
        $search_section = SearchSection::where('position', 'slider_text')->first();
        if($search_section === NULL)
        {
            $search_section = new SearchSection;
            $search_section->position = 'slider_text';
            $search_section->save();
        }
        return view('dashboard.slider.text')->with(['search_section'=>$search_section]);
    }

    public function save_slider_text (Request $request)
    {
        $search_section = SearchSection::where('position', 'slider_text')->first();
        if($search_section === NULL)
        {
            $search_section = new SearchSection;
            $search_section->position = 'slider_text';
            $search_section->save();
        }
        $search_section->title = $request->title;        
        $search_section->text = $request->text;
        $search_section->save();
        
        return redirect()->back();
    }
}

resources/views/dashboard/slider/create.blade.php
@extends('layouts.dashboard')
@section('content')
<!--begin::Portlet-->
<div class="kt-portlet">
	<div class="kt-portlet__head">
		<div class="kt-portlet__head-label">
			<h3 class="kt-portlet__head-title">Add Image</h3>
		</div>
	</div>

	<!--begin::Form-->
	<form class="kt-form kt-form--label-left" id="kt_form_1" method="post"  action="{{ route('slider.store') }}" enctype="multipart/form-data">
		{{ csrf_field() }}
		<div class="kt-portlet__body">
		
									
			<div class="form-group m-form__group row">
				<label class="col-lg-2 col-form-label">Image <small class="d-none">(1920 * 700)</small></label>
				<div class="col-lg-10">
					<div class="custom-file">
						<input type="file" class="custom-file-input" name="image" id="image" />
						<label class="custom-file-label" for="image">Choose file</label>
					</div>
				</div>
			</div>
								
			<div class="kt-portlet__foot">
				<div class="kt-form__actions">
					<div class="row">
						<div class="col-lg-12 text-right">
							<button type="submit" class="btn btn-success">Save</button>
						</div>
					</div>
				</div>
			</div>
		</form>
		<!--end::Form-->
	</div>
@endsection

resources/views/dashboard/slider/edit.blade.php
@extends('layouts.dashboard')
@section('content')
<!--begin::Portlet-->
<div class="kt-portlet">
	<div class="kt-portlet__head">
		<div class="kt-portlet__head-label">
			<h3 class="kt-portlet__head-title">
				Edit Slider
			</h3>
		</div>
	</div>

<!--begin::Form-->
<form class="m-form m-form--label-align-left" method="post" action="{{route('slider.update', $slider->id)}}" enctype="multipart/form-data">
		{{ csrf_field() }}
		<input type="hidden" name="_method" value="PUT" />
		
	<div class="kt-portlet__body">
		@if($errors->any())
			<div class="alert alert-danger">{{$errors->first()}}</div>
		@endif
				
			<div class="form-group m-form__group row">
				<label class="col-lg-2 col-form-label">Image  <small class="d-none">(1920 * 700)</small></label>
				<div class="col-lg-7">
					<div class="custom-file">
						<input type="file" class="custom-file-input" name="image" id="image" />
						<label class="custom-file-label" for="image">Choose file</label>
					</div>
				</div>
				<div class="col-lg-3">
					<img src="{{asset($slider->image)}}">
				</div>
			</div>			
		</div>

		<div class="kt-portlet__foot">
				<div class="kt-form__actions">
					<div class="row">
						<div class="col-lg-12 text-right">
							<button type="submit" class="btn btn-success">Save</button>
						</div>
					</div>
				</div>
			</div>
		</form>
		<!--end::Form-->
	</div>

@endsection

resources/views/dashboard/slider/index.blade.php
@extends('layouts.dashboard')
@section('content')
	<!--begin::Portlet-->
    <div class="kt-portlet">
        <div class="kt-portlet__head">
            <div class="kt-portlet__head-label">
                <h3 class="kt-portlet__head-title">
                    Slider
                </h3>
            </div>
            
            <div class="kt-portlet__head-toolbar">
            	<div class="kt-portlet__head-wrapper">
                	<div class="kt-portlet__head-actions">
                    	<a href="{{url('admin/slider/create')}}" class="btn btn-brand btn-elevate btn-icon-sm"><i class="fas fa-plus"></i> New Image</a>
                    	<a href="{{url('admin/slider_text')}}" class="btn btn-dark btn-elevate btn-icon-sm"><i class="fas fa-edit"></i> Search Section</a>
                    </div>
                </div>
            </div>

        </div>
        <div class="kt-portlet__body">

            <!--begin::Section-->
            <div class="kt-section">
                
                <div class="kt-section__content">
                        <div class="row">

                        @foreach ($sliders as $slider)
                        <div class="col-sm-4">
                        <div class="slider_solo">
                        <img src="{{asset($slider->image)}}" style="height:auto;" />
                        <div class="action_btns">
                        <a href="{{route('slider.edit', $slider->id)}}" class="btn btn-info btn-sm"><i class="fas fa-edit"></i> Edit</a>
                        <a data-toggle="modal" href="#myModal-{{ $slider->id }}" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> Delete</a>
                        </div>
                        
                        <div class="modal fade" id="myModal-{{ $slider->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                        <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Delete Image</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            </button>
                        </div>
                        <div class="modal-body">
                        <form role="form" action="{{ url('/admin/slider/'.$slider->id) }}" class="" method="POST">
                        <input name="_method" type="hidden" value="DELETE">
                        {{ csrf_field() }}
                        <p>Are You Sure?</p>
                        <button type="submit" class="btn btn-danger" name='delete_modal'><i class="fa fa-trash" aria-hidden="true"></i> Delete</button>
                        </form>
                        </div>
                        </div>
                        </div>
                        </div>
                                            
                        </div>
                        </div>
                        @endforeach
                        </div>
                        
                </div>
            </div>

            <!--end::Section-->
        </div>

        <!--end::Form-->
    </div>

    <!--end::Portlet-->
@endsection

resources/views/dashboard/slider/text.blade.php
@extends('layouts.dashboard')
@section('content')
<!--begin::Portlet-->
<div class="kt-portlet">
	<div class="kt-portlet__head">
		<div class="kt-portlet__head-label">
			<h3 class="kt-portlet__head-title">Search Section Text - Slider</h3>
		</div>
	</div>

	<!--begin::Form-->
	<form class="kt-form kt-form--label-left" id="kt_form_1" method="post"  action="{{ url('admin/slider_text') }}" enctype="multipart/form-data">
		{{ csrf_field() }}
		<div class="kt-portlet__body">
		
									
			<div class="form-group m-form__group row">
				<label class="col-lg-2 col-form-label">Title</label>
				<div class="col-lg-10">
					<textarea class="form-control ckeditor" name="title">{{$search_section->title}}</textarea>
				</div>
			</div>

			<div class="form-group m-form__group row">
				<label class="col-lg-2 col-form-label">Text</label>
				<div class="col-lg-10">
					<textarea class="form-control" name="text">{{$search_section->text}}</textarea>
				</div>
			</div>

			<div class="kt-portlet__foot">
				<div class="kt-form__actions">
					<div class="row">
						<div class="col-lg-12 text-right">
							<button type="submit" class="btn btn-success">Save</button>
						</div>
					</div>
				</div>
			</div>
		</form>
		<!--end::Form-->
	</div>
@endsection