routes/web.php
<?php

Auth::routes();
/**
 * *******************************************
 * Admin Routes ********************************
 * *******************************************
 */

Route::match(['get','post'],'/admin','AdminController@login')->name('loginAdmin');
Route::get('login','AdminController@loginform');
Route::get('admin/login','AdminController@loginform')->name('login');

Route::group(['middleware' => ['admin', 'auth'], 'namespace' => 'Admin', 'prefix' => 'admin'],function () {
    Route::post('logout','AdminController@logout')->name('adminLogout');
    // dashboard home
    Route::get('dashboard', 'HomeController@index');
    Route::get('importFile', 'HomeController@create');
    Route::post('importFile', 'HomeController@store');

    // Users Routes
    Route::resource('users', 'UsersController');
    Route::get('users/{id}/status', 'UsersController@status');
    Route::get('users/{id}/delete', 'UsersController@destroy');
    Route::post('users_ajax', 'UsersController@users');

    // Managers Routes
    Route::resource('managers', 'ManagersController');
    Route::get('managers/{id}/status', 'ManagersController@status');
    Route::get('managers/{id}/delete', 'ManagersController@destroy');
    Route::post('managers_ajax', 'ManagersController@managers');

    // Dictionaries Routes
    Route::resource('dictionaries', 'DictionariesController');
    Route::get('dictionaries/{id}/status', 'DictionariesController@status');
    Route::get('dictionaries/{id}/delete', 'DictionariesController@destroy');
    Route::post('dictionaries_ajax', 'DictionariesController@dictionaries');

    // Countries Routes
    Route::resource('countries', 'CountriesController');
    Route::get('countries/{id}/status', 'CountriesController@status');
    Route::get('countries/{id}/delete', 'CountriesController@destroy');
    Route::post('countries_ajax', 'CountriesController@countries');

    // Cities Routes
    Route::resource('cities', 'CitiesController');
    Route::get('cities/{id}/status', 'CitiesController@status');
    Route::get('cities/{id}/delete', 'CitiesController@destroy');
    Route::post('cities_ajax', 'CitiesController@cities');

    // Permissions Routes
    Route::resource('roles', 'RolesController');
    Route::post('roles_ajax', 'RolesController@roles');

    // Languages Routes
    Route::resource('languages', 'LanguagesController');
    Route::get('languages/{id}/delete', 'LanguagesController@destroy');
    Route::post('languages_ajax', 'LanguagesController@languages');

    // Jobs Routes
    Route::resource('jobs', 'JobsController');
    Route::get('jobs/{id}/delete', 'JobsController@destroy');
    Route::post('jobs_ajax', 'JobsController@jobs');
     // Jobs Routes
     Route::resource('categories', 'CategoriesController');
     Route::get('categories_new', 'CategoriesController@new_index');
     Route::get('categories/{id}/delete', 'CategoriesController@destroy');
     Route::post('categories_ajax', 'CategoriesController@categories');
     Route::post('categories_ajax/{id}', 'CategoriesController@sub_categories');

     Route::post('sub_categories_dropdown', 'CategoriesController@sub_categories_dropdown');
     
     // Dictionaries Routes
     Route::resource('dictionaries', 'DictionariesController');
     Route::get('dictionaries/{id}/status', 'DictionariesController@status');
     Route::get('dictionaries/{id}/delete', 'DictionariesController@destroy');
     Route::post('dictionaries_ajax', 'DictionariesController@dictionaries');
     // Books Routes
     Route::resource('books', 'BooksController');
     Route::get('books/{id}/status', 'BooksController@status');
     Route::get('books/{id}/delete', 'BooksController@destroy');
     Route::post('books_ajax', 'BooksController@books');
     // words Routes
     Route::get('words_create_file/{id}', 'WordsController@create_file');
     Route::resource('words', 'WordsController');
     Route::resource('dictionary_file', 'DictionaryFileController');
     Route::get('words/{id}/delete', 'WordsController@destroy');
     Route::get('dictionary_file/{id}/delete', 'DictionaryFileController@destroy');
     Route::post('words_ajax', 'WordsController@words');

     Route::get('media/{id}', 'WordsController@media');
     Route::get('examples/{id}', 'WordsController@examples');

     // words Routes
     Route::resource('search', 'SearchController');
     Route::post('results_ajax', 'SearchController@results_ajax');

     // Home Page Slider
     Route::resource('slider', 'SliderController');
     Route::get('slider_text', 'SliderController@slider_text');
     Route::post('slider_text', 'SliderController@save_slider_text');
        
     // Banner Under Slider
     Route::get('banner_under_slider', 'HomePageController@banner');
     Route::post('banner_under_slider', 'HomePageController@save_banner');
        
     // Home Categories Section
     Route::get('categories_section', 'HomePageController@categories_section');
     Route::post('categories_section', 'HomePageController@save_categories_section');   
             
     // Home About Us Section
     Route::get('home_about_us', 'HomePageController@home_about_us');
     Route::post('home_about_us', 'HomePageController@save_home_about_us');  
     Route::resource('home_about_us_sections', 'HomeAboutController');
     
    Route::get('search_words', 'HomePageController@search_words');
    Route::post('search_words', 'HomePageController@save_search_words');      

    Route::get('work_process', 'HomePageController@work_process');
    Route::post('work_process', 'HomePageController@save_work_process');      
    Route::resource('home_work_process_sections', 'HomeProcessController');
});

/**
 * *******************************************
 * Web Routes ********************************
 * *******************************************
 */

Route::group(['middleware' => 'FrontEnd'],function () {
    // Home Page
    Route::get('/', 'HomeController@index');
    // Contact Us
    Route::get('Contact-Us', 'HomeController@contact');
    Route::post('Contact-Us', 'HomeController@send_contact');    
    // Search Words
    Route::get('Search', 'HomeController@search');
    // Library
    Route::get('Library', 'LibraryController@index');    
    Route::get('Library-File/{id}', 'LibraryController@show');        
    // Blog
    Route::get('Blog', 'BlogController@index');    
    Route::get('User-Articles/{id}', 'BlogController@user_articles');
    Route::get('View-Resume/{id}', 'UserController@view_resume');
    Route::get('Article/{id}', 'BlogController@article');            
    // Register
    Route::get('Register', 'UserController@register_form');
    Route::post('Register', 'UserController@register');
    // Login
    Route::post('Login', 'UserController@login');
    Route::get('activate_account/{token}', 'UserController@activate_account');
    // Subscribe
    Route::post('subscribe', 'HomeController@subscribe');
    
    Route::post('word-comments/{id}', 'WordController@word_comments');
    Route::post('word_comment', 'WordController@save_word_comments');

    Route::post('word-suggestions/{id}', 'WordController@word_suggestions');
    Route::post('word_suggestions', 'WordController@save_word_suggestions');
    Route::post('like_suggesations/{id}', 'WordController@like_suggesations');
    Route::post('dislike_suggesations/{id}', 'WordController@dislike_suggesations');

    Route::post('word-articles/{id}', 'WordController@word_articles');


    Route::group(['middleware' => 'auth'],function () {
        Route::get('Profile', 'UserController@profile');

        Route::get('Favourite-Word/{id}', 'UserController@favourite_word');
        Route::post('Favourite-Book/{id}', 'UserController@favourite_book');

        Route::get('Change-Information', 'UserController@change_information');
        Route::post('Change-Information', 'UserController@save_information');
 
        Route::get('Change-Password', 'UserController@change_password');
        Route::post('Change-Password', 'UserController@save_password');

        Route::get('My-Resume', 'UserResumeController@index');
        Route::get('Preview-Resume', 'UserController@preview_resume');
        Route::post('Cover-Letter', 'UserResumeController@cover_letter');

        
        Route::post('New-Education', 'UserResumeController@new_education');
        Route::post('Update-Education/{id}', 'UserResumeController@update_education');
        Route::get('delete_education/{id}', 'UserResumeController@delete_education');

        Route::post('New-Experince', 'UserResumeController@new_experince');
        Route::post('Update-Experince/{id}', 'UserResumeController@update_experince');
        Route::get('delete_experince/{id}', 'UserResumeController@delete_experince');

        Route::post('Skills', 'UserResumeController@skills');
        Route::post('add_skill', 'UserResumeController@add_skill');

        Route::post('Languages', 'UserResumeController@languages');
        Route::post('add_language', 'UserResumeController@add_language');

        Route::post('New-Award', 'UserResumeController@new_award');
        Route::post('Update-Award/{id}', 'UserResumeController@update_award');
        Route::get('delete_award/{id}', 'UserResumeController@delete_award');

        Route::get('My-Blog', 'UserBlogController@index');        
        Route::get('New-Article', 'UserBlogController@create');        
        Route::get('New-Article/{word}', 'UserBlogController@create_wword');
        Route::post('Post-Article', 'UserBlogController@store');        
        Route::get('Edit-Article/{id}', 'UserBlogController@edit');        
        Route::post('Update-Article/{id}', 'UserBlogController@update');        
        Route::get('Delete-Article/{id}', 'UserBlogController@destroy');        
        Route::post('article_comment', 'UserBlogController@article_comment');        
        
        Route::get('My-Library', 'UserLibraryController@index');        

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Category_trans;
use App\Http\Controllers\Controller;
use App\Language;
use Validator;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Auth;

use Intervention\Image\ImageManagerStatic as Image;

class CategoriesController extends Controller
{
    use AjaxData;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function new_index()
    {
        $main_category = NULL;
        $data = Category::where('sub_from', 0)->count();
        return view('dashboard.categories.index', ['data' => $data, 'main_category'=> $main_category]);
    }

    public function index()
    {
        $main_category = NULL;
        $data = Category::where('sub_from', 0)->count();
        $cats = Category::where('sub_from', 0)->get();
        return view('dashboard.categories.new_index', ['data' => $data, 'main_category'=> $main_category, 'cats'=>$cats]);
    }
    
    public function show($id)
    {
        $main_category = Category::findorfail($id);
        $data = Category::where('sub_from', $id)->count();
        return view('dashboard.categories.index', ['data' => $data, 'main_category' => $main_category]);
    }

    /**
     * Categories ajax DT
     */
    public function categories(){
        $data = Category::where('sub_from', 0)->get();

        return $this->dataResponse($data);
    }
    public function sub_categories($id){
        $main_category = Category::findorfail($id);
        $data = Category::where('sub_from', $id)->get();
        return $this->dataResponse($data);
    }
    
    public function sub_categories_dropdown(Request $request){
        $main_category = Category::findorfail($request->cat);
        $data = Category::where('sub_from', $request->cat)->get();
        ?>
        <option value="">Choose Category</option>
        <?php
        foreach($data as $category)
        {
            ?>
            <option value="<?php echo $category->id; ?>"><?php echo $category->title; ?></option>
            <?php
        }
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::where('sub_from', 0)->get();

        return view('dashboard.categories/create', ['categories' => $categories, 'page_name' => 'Add new category']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = [
            'title' => 'required',
        ];

        $attr = [
            'title' => 'Title',
        ];

        $validator = Validator::make($request->all(), $data, [], $attr);

        if ($validator->fails()) {
            return back()
                    ->withErrors($validator)
                    ->withInput();
        }

        $category = new Category();
        $category->title = $request->title;
        $category->sub_from = $request->sub_from;
        if($request->hasFile('icon'))
        {
            $validatedData = $request->validate([
                'icon' => 'required|mimes:jpeg,png,jpg,gif,svg,webp'
            ],
            $messages = [
                'icon.required' => 'Please Choose Image',
                'icon.mimes' => 'Please Choose Image'
            ]);

            $image = $request->file('icon');
            $imageName = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/uploads/dictionary_categories');
            $image->move($destinationPath, $imageName);
            $category->icon = '/uploads/dictionary_categories/'.$imageName;
            $image = Image::make(public_path().$category->icon)->resize(null, 71, function ($constraint) {$constraint->aspectRatio();})->save(public_path().$category->icon);
        }
        
        $category->save();

        
        return redirect()->route('categories.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Category::findOrFail($id);

        $categories = Category::where('sub_from', 0)->get();

        return view('dashboard.categories/edit', ['categories' => $categories, 'data' => $data, 'page_name' => 'Edit category']);
    }

    /**
     * change status
     */

    public function status($id){
        $data = Category::findOrFail($id);
        $status = $data->status == 0 ? 1 : 0;

        $data->update(['status' => $status]);

        return back()->with('success', 'Success');
     }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);

        $data = [
            'title' => 'required',
        ];

        $attr = [
            'title' => 'الإسم',
        ];

        $validator = Validator::make($request->all(), $data, [], $attr);

        if ($validator->fails()) {
            return back()
                    ->withErrors($validator)
                    ->withInput();
        }

        $category->title = $request->title;
        $category->sub_from = $request->sub_from;
                if($request->hasFile('icon'))
        {
            $validatedData = $request->validate([
                'icon' => 'required|mimes:jpeg,png,jpg,gif,svg,webp'
            ],
            $messages = [
                'icon.required' => 'Please Choose Image',
                'icon.mimes' => 'Please Choose Image'
            ]);

            if (File::exists(public_path().$category->icon))
            {
                File::delete(public_path().$category->icon);
            }

            $image = $request->file('icon');
            $imageName = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/uploads/dictionary_categories');
            $image->move($destinationPath, $imageName);
            $category->icon = '/uploads/dictionary_categories/'.$imageName;
            $image = Image::make(public_path().$category->icon)->resize(null, 71, function ($constraint) {$constraint->aspectRatio();})->save(public_path().$category->icon);
        }

        $category->save();

        return redirect()->back()->with('success', 'Success update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();
        return redirect()->back()->with('success', 'Removed');
    }
}

resources/views/dashboard/categories/create.blade.php
@extends('layouts.dashboard')
@section('content')
<!-- begin:: Content -->
<div class="kt-container kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="kt-wizard-v4" id="kt_user_add_user" data-ktwizard-state="step-first">
        <!--end: Form Wizard Nav -->
        <div class="kt-portlet">
            <div class="kt-portlet__body kt-portlet__body--fit">
                <div class="kt-grid">
                    <div class="kt-grid__item kt-grid__item--fluid kt-wizard-v4__wrapper">
                        <!--begin: Form Wizard Form-->
                        <form class="kt-form" id="kt_user_add_form" method="POST" action="{{ route('categories.store') }}" enctype="multipart/form-data">
                            <!--begin: Form Wizard Step 1-->
                            @csrf
                            <div class="kt-wizard-v4__content" data-ktwizard-type="step-content"
                                data-ktwizard-state="current">
                                <div class="kt-heading kt-heading--md">Add new category :</div>
                                <div class="kt-section kt-section--first">
                                    <div class="kt-wizard-v4__form">
                                        <div class="row">
                                            <div class="col-xl-12">
                                                <div class="kt-section__body">
                                                    <div class="form-group row">
                                                        <label class="col-xl-3 col-lg-3 col-form-label">Title</label>
                                                        <div class="col-lg-9 col-xl-9">
                                                            <input class="form-control" name="title" type="text" value="{{ old('title') }}">
                                                        </div>
                                                    </div>
                                                    
                                                    <div class="form-group row">
                                                        <label class="col-xl-3 col-lg-3 col-form-label">Icon</label>
                                                        <div class="col-lg-9 col-xl-9">
                                                            <input class="form-control" name="icon" type="file" />
                                                        </div>
                                                    </div>
                                                    
                                                    <div class="form-group row">
                                                        <label class="col-xl-3 col-lg-3 col-form-label">Type
                                                        </label>
                                                        <div class="col-lg-9 col-xl-9">
                                                            <div class="form-group">
                                                                <div class="kt-radio-inline">
                                                                    <label class="kt-radio">
                                                                        <input type="radio" class="custom-radio category_checker" name="type" 
                                                                        value="0" checked /> Main
                                                                        <span></span>
                                                                    </label>
                                                                    <label class="kt-radio">
                                                                        <input type="radio" class="custom-radio category_checker" name="type" 
                                                                        value="1" /> Sub
                                                                        <span></span>
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group row d-none" id="category_checker_red">
                                                        <label class="col-xl-3 col-lg-3 col-form-label">Sub From
                                                        </label>
                                                        <div class="col-lg-9 col-xl-9">
                                                            <div class="form-input">
                                                                <select name="sub_from" class="form-control select2 selectpicker">
                                                                    <option value="0">Choose Category</option>
                                                                    @foreach($categories as $category)
                                                                        <option value="{{$category->id}}">{{ $category->title }}</option>
                                                                    @endforeach
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--end: Form Wizard Step 1-->
                            <!--begin: Form Actions -->
                            <div class="kt-form__actions">
                                <button type="submit"
                                    class="btn btn-primary btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u">Add</button>
                            </div>
                            <!--end: Form Actions -->
                        </form>
                        <!--end: Form Wizard Form-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end:: Content -->
@endsection


@section('footer-js')
<script>
$(document).ready(function(){
        $('body').on('change', '.category_checker', function(){
        var aa = $(this).val();

        if(aa == '0')
        {
            $('#category_checker_red').addClass('d-none');
        }
        else
        {
            $('#category_checker_red').removeClass('d-none');
        }
	});
});
</script>
@endsection

resources/views/dashboard/categories/edit.blade.php
@extends('layouts.dashboard')
@section('content')
<!-- begin:: Content -->
<div class="kt-container kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="kt-wizard-v4" id="kt_user_add_user" data-ktwizard-state="step-first">
        <!--end: Form Wizard Nav -->
        <div class="kt-portlet">
            <div class="kt-portlet__body kt-portlet__body--fit">
                <div class="kt-grid">
                    <div class="kt-grid__item kt-grid__item--fluid kt-wizard-v4__wrapper">
                        <!--begin: Form Wizard Form-->
                        <form class="kt-form" id="kt_user_add_form" method="POST" action="{{ route('categories.update', $data->id) }}" enctype="multipart/form-data">
                            <!--begin: Form Wizard Step 1-->
                            @csrf
                            @method('PUT')
                            <div class="kt-wizard-v4__content" data-ktwizard-type="step-content"
                                data-ktwizard-state="current">
                                <div class="kt-heading kt-heading--md">Edit category :</div>
                                <div class="kt-section kt-section--first">
                                    <div class="kt-wizard-v4__form">
                                        <div class="row">
                                            <div class="col-xl-12">
                                                <div class="kt-section__body">
                                                    <div class="form-group row">
                                                        <label class="col-xl-3 col-lg-3 col-form-label">Title</label>
                                                        <div class="col-lg-9 col-xl-9">
                                                            <input class="form-control" name="title" type="text" value="{{ $data->title }}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <label class="col-xl-3 col-lg-3 col-form-label">Icon</label>
                                                        <div class="col-lg-6 col-xl-6">
                                                            <input class="form-control" name="icon" type="file" />
                                                        </div>
                                                        <div class="col-xl-3 col-lg-3">
                                                            @if($data->icon != '')
                                                            <img src="{{asset($data->icon)}}" />
                                                            @endif
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <label class="col-xl-3 col-lg-3 col-form-label">Type
                                                        </label>
                                                        <div class="col-lg-9 col-xl-9">
                                                            <div class="form-group">
                                                                <div class="kt-radio-inline">
                                                                    <label class="kt-radio">
                                                                        <input type="radio" class="custom-radio category_checker" name="type" value="0" {{ $data->sub_from == 0 ? 'checked' : '' }}/> Main
                                                                        <span></span>
                                                                    </label>
                                                                    <label class="kt-radio">
                                                                        <input type="radio" class="custom-radio category_checker" 
                                                                        name="type" value="1" {{ $data->sub_from != 0 ? 'checked' : '' }}/> Sub
                                                                        <span></span>
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group row @if($data->sub_from == 0) d-none @endif" id="category_checker_red">
                                                        <label class="col-xl-3 col-lg-3 col-form-label">Sub From
                                                        </label>
                                                        <div class="col-lg-9 col-xl-9">
                                                            <div class="form-input">
                                                                <select name="sub_from" class="form-control select2 selectpicker">
                                                                    <option value="0">Choose Category</option>
                                                                    @foreach($categories as $category)
                                                                        <option value="{{$category->id}}" {{ $data->sub_from == $category->id ? 'selected' : '' }}>{{ $category->title }}</option>
                                                                    @endforeach
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--end: Form Wizard Step 1-->
                            <!--begin: Form Actions -->
                            <div class="kt-form__actions">
                                <button type="submit"
                                    class="btn btn-success btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u">Save</button>
                            </div>
                            <!--end: Form Actions -->
                        </form>
                        <!--end: Form Wizard Form-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end:: Content -->
@endsection

@section('footer-js')
<script>
$(document).ready(function(){
    $('body').on('change', '.category_checker', function(){
        var aa = $(this).val();


        if(aa == '0')
        {
            $('#category_checker_red').addClass('d-none');
        }
        else
        {
            $('#category_checker_red').removeClass('d-none');
        }
	});
});
</script>
@endsection